<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>14</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lib7\Lib7.csproj" />
    <ProjectReference Include="..\Lib10\Lib10.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Framework.cs" />
  </ItemGroup>
</Project>
