<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>14</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Lib1\Lib1.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\Framework.cs" />
  </ItemGroup>
</Project>
